spring:
  profiles:
    active: prod
  application:
    name: rothschil-common
  datasource:
#    url： jdbc:h2:file:./data/embedded;DB_CLOSE_DELAY=-1
    url: jdbc:h2:mem:embedded
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    #        use_sql_comments: true
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        enable_lazy_load_no_trans: true
    generate-ddl: false
  transaction:
    rollback-on-commit-failure: true
  h2:
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: true
    console.enabled: true

logging:
  config: classpath:logback-spring.xml
dynamic:
  enabled: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl