spring:
  profiles:
    active: prod
  application:
    name: rothschil-common
  datasource:
    druid:
      master:
        name: ds_h2
        driver-class-name: org.h2.Driver
        #基本属性
        url: jdbc:h2:file:D:/Code/Gradle/rothschil-common/Doc/h2/Repertory/memdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;MODE=PostgreSQL;
        username: sa
        password: 123456
        test-while-idle: false
      salve:
        name: ds_sqlite
        driver-class-name: org.sqlite.JDBC
        #基本属性
        url: jdbc:h2:file:D:/Code/Gradle/rothschil-common/Doc/h2/Repertory/memdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;MODE=PostgreSQL;
        username: sa
        password: 123456
        test-while-idle: false
      use-global-data-source-stat: true
      #监控统计拦截的filters
      filters: stat
      #配置初始化大小/最小/最大
      initial-size: 2
      min-idle: 2
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x' FROM DUAL
      # mysql需要设置校验
      # 指明是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个.注意: 设置为true后如果要生效,validationQuery参数必须设置为非空字符串
      test-while-idle: false
      # 指明是否在归还到池中前进行检验  注意: 设置为true后如果要生效,validationQuery参数必须设置为非空字符串
      test-on-borrow: false
      # 指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除. 注意: 设置为true后如果要生效,validationQuery参数必须设置为非空字符串
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    #        use_sql_comments: true
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        enable_lazy_load_no_trans: true
    generate-ddl: false
    defer-datasource-initialization: true
  transaction:
    rollback-on-commit-failure: true
  h2:
    console:
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true
      enabled: true
  jackson:
    # json 序列化排除值为 null 的属性
    default-property-inclusion: non_null
    # 配置 Date 类的时间格式，如果不涉及可以不加
    date-format: yyyy-MM-dd HH:mm:ss
    # 配置 Date 类的时区，如果不涉及可以不加
    time-zone: GMT+8
  cache:
    type: composite
    caffeine:
      spec: maximumSize=500,expireAfterWrite=60s
    redis:
      database: 0
      host: localhost
      port: 6379
      password:
      timeout: 5000
  redis:
    redisson:
      file: classpath:redisson.yml
logging:
  config: classpath:logback-spring.xml
dynamic:
  enabled: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl