spring:
  profiles:
    active: prod
  application:
    name: rothschil-common

logging:
  config: classpath:logback-spring.xml

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl